name: ARM64 build

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'arm64v8/python:3.7.5-buster'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/arm64"
          echo 'FROM "${image}"' > Dockerfile
          echo '\nRUN pip3 install scikit-learn==1.0.1 six==1.16.0 scipy==1.7.2 PyWavelets==1.2.0 python-dateutil==2.8.2 pyparsing==3.0.6 cycler==0.11.0 grpcio==1.41.1 grpcio-tools==1.41.1 kiwisolver==1.3.2 matplotlib==3.4.3 numpy==1.21.4 Pillow==8.4.0 protobuf==3.19.1 pymongo==3.12.1' >>  Dockerfile
          docker build -t pyarm64-alg .
          docker save pyarm64-alg -o "${image//\//_}-arm64.tar"
        done

    - name: Compress the TAR files
      run: tar -czf arm64-images.tar.gz *-arm64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: arm64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-arm64.tar
